<?php

/**
 * Registration with Phone no template
 *
 * @var $block \Magento\Framework\View\Element\Template
 */
?>
<div class="field phone_number required">
    <label class="label" for="phone_number">
        <span><?= $escaper->escapeHtml(__('Telephone')) ?></span>
    </label>
    <div class="control">
        <input type="text" name="phone_number" id="phone_number" value=""
            title="<?= $escaper->escapeHtml(__('Telephone')) ?>"
            class="input-text" data-validate="{required:true}">
    </div>
</div>